/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_antelop_jni_example_HelloWorld */

#ifndef _Included_org_antelop_jni_example_HelloWorld
#define _Included_org_antelop_jni_example_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_antelop_jni_example_HelloWorld
 * Method:    displayHelloWorld1
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_org_antelop_jni_example_HelloWorld_displayHelloWorld1
  (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
